/**
 * Generated by app/scripts/download-gotsport-crests.js – do not edit by hand.
 * Run: node app/scripts/download-gotsport-crests.js
 */
import type { ImageSourcePropType } from 'react-native';

export const TEAM_CREST_SOURCES: Record<string, ImageSourcePropType> = {
  'Oxford City FC U14 Girls': require('../assets/team_crests/oxford-city-fc-u14-girls.gif'),
  'Milton Keynes Dons SET - Girls Milton Keynes Dons Girls Performance U14s': require('../assets/team_crests/milton-keynes-dons-set-girls-milton-keynes-dons-girls-performance-u14s.png'),
  'Northampton Town Women FC U14': require('../assets/team_crests/northampton-town-women-fc-u14.jpeg'),
  'St Albans City FC Academy - Girls U14 Girls': require('../assets/team_crests/st-albans-city-fc-academy-girls-u14-girls.png'),
  'Aylesbury United Women FC U14': require('../assets/team_crests/aylesbury-united-women-fc-u14.png'),
  'Prestbury Phantoms Youth AFC U14 Trojans': require('../assets/team_crests/prestbury-phantoms-youth-afc-u14-trojans.png'),
  'Luton Town Ladies FC Youth U14 Wanderers': require('../assets/team_crests/luton-town-ladies-fc-youth-u14-wanderers.png'),
  'Stevenage Football Club U14': require('../assets/team_crests/stevenage-football-club-u14.png'),
  'Capital Girls U14 Girls': require('../assets/team_crests/capital-girls-u14-girls.jpeg'),
  'Atletico London U14 Dragons': require('../assets/team_crests/atletico-london-u14-dragons.png'),
};
